server:
  port: 8085
  error:
    include-stacktrace: never
spring:
  application:
    name: camus-jwt-webflux
  devtools:
    add-properties: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
jwt:
  tokenSecret: qwer1234!@#$asdfjiewanfgeirngreiugerliuWD #todo: encrypt
  expirationMs: 3600000
