server:
  port: 8082
  error:
    include-stacktrace: never
spring:
  application:
    name: camus-orm-jpa
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      mode: always
