server:
  port: 8082
  error:
    include-stacktrace: never
spring:
  application:
    name: database-jpa
  devtools:
    add-properties: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      mode: always
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
