server:
  port: 9090
spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    producer:
      properties:
        schema:
          registry:
            url: http://localhost:8081
        specific:
          avro:
            reader: true
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html