server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            filterName: GlobalFilter
        - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - OPTIONS
              - POST
              - GET
              - PUT
              - DELETE
      routes:
        - id: example-api
          uri: lb://EXAMPLE-API
          predicates:
            - Path=/example-api/**
        - id: example-api
          uri: lb://EXAMPLE-API
          predicates:
            - Path=/example-api/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/example-api/(?<path>.*), /$\{path}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh