server:
  port: 9002
spring:
  application:
    name: camus-feign-task
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  pattern:
    level: '%5p {applicationName: ${spring.application.name:}, traceId: %X{traceId:-}, spanId: %X{spanId:-}}'